version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/swangeese-mainpage

    steps:
      - checkout

      - run: git submodule sync
      - run: git submodule update --init
      - run: git config --global user.email "CircleCI@USTC-SwanGeese.github.io"
      - run: git config --global user.name "CircleCI"
      - add_ssh_keys:
          fingerprints:
            - "f3:c3:d2:6d:4c:5b:c3:3f:26:6e:ac:80:59:27:e2:82"

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm update

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - deploy:
          command: ./node_modules/hexo/bin/hexo deploy --generate
