version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/swangeese-mainpage

    steps:
      - checkout

      - run: git submodule sync
      - run: git submodule update --init
      - run: git config --global user.email "CircleCI@USTC-SwanGeese.github.io"
      - run: git config --global user.name "CircleCI"

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm update

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - deploy:
          command: ./node_modules/hexo/bin/hexo deploy --generate
